---
- name: Install ssmtp
  apt:
    name: ssmtp
    state: "{{ ssmtp_package_state | default(apt_package_state) }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: ssmtp configuration
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
